name: First CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rid: ["win-x64", "linux-x64"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - run: dotnet restore
      - run: dotnet build
      - run: dotnet test
      - run: dotnet publish -o app-${{ matrix.rid }} -r ${{ matrix.rid }} --sc /p:PublishSingleFile=true,AssemblyName=app
      - run: tar cf app-${{ matrix.rid }}.tar app-${{ matrix.rid }}/
      - uses: actions/upload-artifact@v4
        with:
          name: app-${{ matrix.rid }}
          path: app-${{ matrix.rid }}.tar
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: app-linux-x64
      - run: tar xf app-linux-x64.tar
      - run: chmod +x app-linux-x64/app
      - run: ./app-linux-x64/app